// Copyright (c) Meta Platforms, Inc. and affiliates.

#include "comms/ctran/algos/ReduceScatter/ReduceScatterDirect.cuh"

// Explicit template instantiations for ReduceScatterDirect kernels
// For each data type, instantiate for all reduction operations: Sum, Prod, Avg, Max, Min

#define INSTANTIATE_REDUCESCATTER_DIRECT(T) \
  DECL_CTRAN_REDUCESCATTERDIRECT_KERN(T, commSum); \
  DECL_CTRAN_REDUCESCATTERDIRECT_KERN(T, commProd); \
  DECL_CTRAN_REDUCESCATTERDIRECT_KERN(T, commAvg); \
  DECL_CTRAN_REDUCESCATTERDIRECT_KERN(T, commMax); \
  DECL_CTRAN_REDUCESCATTERDIRECT_KERN(T, commMin);

INSTANTIATE_REDUCESCATTER_DIRECT(int8_t);
INSTANTIATE_REDUCESCATTER_DIRECT(uint8_t);
INSTANTIATE_REDUCESCATTER_DIRECT(int32_t);
INSTANTIATE_REDUCESCATTER_DIRECT(uint32_t);
INSTANTIATE_REDUCESCATTER_DIRECT(int64_t);
INSTANTIATE_REDUCESCATTER_DIRECT(uint64_t);
INSTANTIATE_REDUCESCATTER_DIRECT(half);
INSTANTIATE_REDUCESCATTER_DIRECT(float);
INSTANTIATE_REDUCESCATTER_DIRECT(double);
#if defined(__CUDA_BF16_TYPES_EXIST__) || defined(__HIP_PLATFORM_AMD__)
INSTANTIATE_REDUCESCATTER_DIRECT(__nv_bfloat16);
#endif
#if defined(__CUDA_FP8_TYPES_EXIST__) && defined(NCCL_ENABLE_FP8)
INSTANTIATE_REDUCESCATTER_DIRECT(__nv_fp8_e4m3);
INSTANTIATE_REDUCESCATTER_DIRECT(__nv_fp8_e5m2);
#endif