// Copyright (c) Meta Platforms, Inc. and affiliates.

#include "comms/ctran/algos/AllToAll/AllToAllvDynamic.cuh"

// Explicit template instantiations for AllToAllvDynamic kernels
DECL_CTRAN_ALLTOALLVDYNAMIC_KERN(int8_t);
DECL_CTRAN_ALLTOALLVDYNAMIC_KERN(uint8_t);
DECL_CTRAN_ALLTOALLVDYNAMIC_KERN(int32_t);
DECL_CTRAN_ALLTOALLVDYNAMIC_KERN(uint32_t);
DECL_CTRAN_ALLTOALLVDYNAMIC_KERN(int64_t);
DECL_CTRAN_ALLTOALLVDYNAMIC_KERN(uint64_t);
DECL_CTRAN_ALLTOALLVDYNAMIC_KERN(half);
DECL_CTRAN_ALLTOALLVDYNAMIC_KERN(float);
DECL_CTRAN_ALLTOALLVDYNAMIC_KERN(double);
#if defined(__CUDA_BF16_TYPES_EXIST__) || defined(__HIP_PLATFORM_AMD__)
DECL_CTRAN_ALLTOALLVDYNAMIC_KERN(__nv_bfloat16);
#endif
#if defined(__CUDA_FP8_TYPES_EXIST__) && defined(NCCL_ENABLE_FP8)
DECL_CTRAN_ALLTOALLVDYNAMIC_KERN(__nv_fp8_e4m3);
DECL_CTRAN_ALLTOALLVDYNAMIC_KERN(__nv_fp8_e5m2);
#endif

// Explicit template instantiations for AllToAllvDynamicSplit kernels
DECL_CTRAN_ALLTOALLVDYNAMIC_SPLIT_KERN(int8_t);
DECL_CTRAN_ALLTOALLVDYNAMIC_SPLIT_KERN(uint8_t);
DECL_CTRAN_ALLTOALLVDYNAMIC_SPLIT_KERN(int32_t);
DECL_CTRAN_ALLTOALLVDYNAMIC_SPLIT_KERN(uint32_t);
DECL_CTRAN_ALLTOALLVDYNAMIC_SPLIT_KERN(int64_t);
DECL_CTRAN_ALLTOALLVDYNAMIC_SPLIT_KERN(uint64_t);
DECL_CTRAN_ALLTOALLVDYNAMIC_SPLIT_KERN(half);
DECL_CTRAN_ALLTOALLVDYNAMIC_SPLIT_KERN(float);
DECL_CTRAN_ALLTOALLVDYNAMIC_SPLIT_KERN(double);
#if defined(__CUDA_BF16_TYPES_EXIST__) || defined(__HIP_PLATFORM_AMD__)
DECL_CTRAN_ALLTOALLVDYNAMIC_SPLIT_KERN(__nv_bfloat16);
#endif
#if defined(__CUDA_FP8_TYPES_EXIST__) && defined(NCCL_ENABLE_FP8)
DECL_CTRAN_ALLTOALLVDYNAMIC_SPLIT_KERN(__nv_fp8_e4m3);
DECL_CTRAN_ALLTOALLVDYNAMIC_SPLIT_KERN(__nv_fp8_e5m2);
#endif

// Explicit template instantiations for AllToAllvDynamicSplitNonContig kernels
DECL_CTRAN_ALLTOALLVDYNAMIC_SPLITNONCONTIG_KERN(int8_t);
DECL_CTRAN_ALLTOALLVDYNAMIC_SPLITNONCONTIG_KERN(uint8_t);
DECL_CTRAN_ALLTOALLVDYNAMIC_SPLITNONCONTIG_KERN(int32_t);
DECL_CTRAN_ALLTOALLVDYNAMIC_SPLITNONCONTIG_KERN(uint32_t);
DECL_CTRAN_ALLTOALLVDYNAMIC_SPLITNONCONTIG_KERN(int64_t);
DECL_CTRAN_ALLTOALLVDYNAMIC_SPLITNONCONTIG_KERN(uint64_t);
DECL_CTRAN_ALLTOALLVDYNAMIC_SPLITNONCONTIG_KERN(half);
DECL_CTRAN_ALLTOALLVDYNAMIC_SPLITNONCONTIG_KERN(float);
DECL_CTRAN_ALLTOALLVDYNAMIC_SPLITNONCONTIG_KERN(double);
#if defined(__CUDA_BF16_TYPES_EXIST__) || defined(__HIP_PLATFORM_AMD__)
DECL_CTRAN_ALLTOALLVDYNAMIC_SPLITNONCONTIG_KERN(__nv_bfloat16);
#endif
#if defined(__CUDA_FP8_TYPES_EXIST__) && defined(NCCL_ENABLE_FP8)
DECL_CTRAN_ALLTOALLVDYNAMIC_SPLITNONCONTIG_KERN(__nv_fp8_e4m3);
DECL_CTRAN_ALLTOALLVDYNAMIC_SPLITNONCONTIG_KERN(__nv_fp8_e5m2);
#endif